---
- hosts: localhost
  gather_facts: no
  # vars_prompt:
  #  - name: "name"
  #    prompt: "Enter name of VM"
  #    private: no
  roles:
   - deployvm

- hosts: deployed_vms
  roles:
   - apache

