---
 - name: Create VM from template
   vmware_guest:
    hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: false
    name: "{{ name }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    folder: "{{ folder }}"
    state: poweredon
    template: "{{ template }}"
    disk:
    - size_gb: 60
      type: thin
      autoselect_datastore: true
    networks:
    - name: "{{ portgroup }}"
      #device_type: e1000e
      ip: "{{ server_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"
      type: static
      start_connected: true
      dns_servers:
      - "{{ dns_ip }}"
    customization:
     dns_servers:
     - "{{ dns_ip }}"
     hostname: '{{ name}}'
    wait_for_ip_address: true
    wait_for_customization: true
   delegate_to: localhost

 - name: "Wait for VM Tools"
   local_action:
    module: vmware_guest_tools_wait
    hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: false
    name: "{{ name }}"

 - name: "Wait for SSH"
   local_action:
    module: wait_for
    host: "{{ server_ip }}"
    port: 22
    timeout: 300
    state: started
    delay: 30

 - name: "Add Provioned VM to temp Host Group"
   add_host:
    name: "{{ server_ip }}"
    groups: webservers
